project:
  type: website
  output-dir: public

website:
  title: "Sarin Tiatragul"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd # add your listing page file to your navbar, just like you would any other new web page
      - divelog.qmd # add your listing page file to your navbar, just like you would any other new web page

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

