project:
  type: website
  output-dir: public

website:
  title: "Sarin Tiatragul"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

